# Generated by Django 4.2.3 on 2023-07-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
